# MISC
seed: 42
registration: mni


# DEBUG
debug: False
data_debug:
  rot90: False
  return_path: False
  aug_verbose: False
run_debug:
  return_all: False


# MODEL
layers: [4, 8, 16, 32]
batchnorm: True # Vres
double: False # Vres
dropout: True # SFCN
channel_number: [32, 64, 128, 256, 64] # SFCN
start_channels: 16 # RESNET


# DATALOADER
test_size: 0.2
batch_size: 16
augment: False
resize: [96, 96, 96]
aug_proba:
  affine: 0.33
  flip: 0.33
  elastic_deform: 0.33
aug_intensity:
  affine: [0.1, 10]
  elastic_deform: [7, .5]
unused_src:
  - ~

  
# TRAIN
epochs: 100
mae_threshold: 8.0
verbose_period: 5
early_patience: 20

model_name: resnet
lamb: 0.0005
learning_rate: 0.0001
scheduler: false
loss: mse
metrics:
  - rmse
  - mae
  - r2
  - corr

# UNLEARNING
unlearn: False
unlearn_cfg:

  metrics:
    - acc
  
  # MODEL SETUP
  encoder:
    name: vanillaconv

  regressor:
    name: nkregressor

  domainer:
    name: nkdomainpredictor
    
  # OPTIMIZER SETTINGS
  regression:
    optimizer: adam
    lr: .0001
    weight_decay: 0
    
  domain:
    optimizer: adam
    lr: .0001
    weight_decay: 0

  confusion:
    optimizer: adam
    lr: .0001
    weight_decay: 0

