# MISC
seed: 42
folds: 20
root: ../../brainmask_tlrc/

# DEBUG
debug: False
_debug:
  rot90: False
  return_path: False
  aug_verbose: False


# MODEL
model_name: resnet
lamb: 0.0005
learning_rate: 0.0001
scheduler: false
loss: mse
metrics:
  - rmse
  - mae
  - r2
resize: [96, 96, 96]
layers: [4, 8, 16, 32]

batchnorm: True # Vres
double: False # Vres
dropout: True # SFCN
channel_number: [32, 64, 128, 256, 64] # SFCN
start_channels: 16 # RESNET

# DATALOADER
test_size: 0.2
batch_size: 16
aug_proba:
  affine: 0.33
  flip: 0.33
  elastic_deform: 0.33
aug_intensity:
  affine: [0.1, 10]
  elastic_deform: [7, .5]
unused_src:
  - ~

# TRAIN
epochs: 100
mae_threshold: 8.0
verbose_period: 5